apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stack }}-{{ .Values.service }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
      name: "{{ .Values.service }}"
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    run: {{ .Values.stack }}-{{ .Values.service }}
  type: ClusterIP
